<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Tripix-e506a19a-f6d1-4b6d-b9a3-417520ac0aaa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.68.0.3427" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.13" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.0-preview.3.25172.1" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.2.0" />
    <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="3.2.0" />
    <PackageReference Include="MimeKit" Version="4.11.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.30.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="136.0.7103.1700-beta" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
    <PackageReference Include="Stripe.net" Version="48.1.0-beta.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\AmrSoliman\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Images\Blogs\" />
    <Folder Include="wwwroot\Images\CarForRent\" />
    <Folder Include="wwwroot\Images\CriminalRecord\" />
    <Folder Include="wwwroot\Images\DriverCar\" />
    <Folder Include="wwwroot\Images\DriverImage\" />
    <Folder Include="wwwroot\Images\DriverLicense\" />
    <Folder Include="wwwroot\Images\ElectricCars\" />
    <Folder Include="wwwroot\Images\Events\" />
    <Folder Include="wwwroot\Images\FaceId\" />
    <Folder Include="wwwroot\Images\JopApplicationCvs\" />
    <Folder Include="wwwroot\Images\Motorbikes\" />
    <Folder Include="wwwroot\Images\TipImages\" />
    <Folder Include="wwwroot\Images\UsedCarImages\" />
  </ItemGroup>

</Project>
