using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Tripix.Abstractions.Consts;
using Tripix.Entities;

namespace Tripix.Context.Config
{
    public class BrandConfig : IEntityTypeConfiguration<CarBrand>
    {
        public void Configure ( EntityTypeBuilder<CarBrand> builder )
        {
            builder.HasData(new List<CarBrand>
            {
               new() { Id = 1, Name = "Toyota", NameAR = " ÊÌÊ «", Expand = false , VehicleType = vehicletype.Car },
               new() { Id = 2, Name = "Hyundai", NameAR = "ÂÌÊ‰œ«Ì", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 3, Name = "Nissan", NameAR = "‰Ì”«‰", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 4, Name = "Kia", NameAR = "ﬂÌ«", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 5, Name = "Chevrolet", NameAR = "‘Ì›—Ê·ÌÂ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 6, Name = "Mercedes", NameAR = "„—”Ìœ”", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 7, Name = "BMW", NameAR = "»Ì ≈„ œ»·ÌÊ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 8, Name = "Honda", NameAR = "ÂÊ‰œ«", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 9, Name = "Ford", NameAR = "›Ê—œ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 10, Name = "Jeep", NameAR = "ÃÌ»", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 11, Name = "Audi", NameAR = "√ÊœÌ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 12, Name = "Mazda", NameAR = "„«“œ«", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 13, Name = "Land Rover", NameAR = "·«‰œ —Ê›—", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 14, Name = "Porsche", NameAR = "»Ê—‘", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 15, Name = "Lexus", NameAR = "·ﬂ“”", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 16, Name = "Jaguar", NameAR = "Ã«ﬂÊ«—", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 17, Name = "Volvo", NameAR = "›Ê·›Ê", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 18, Name = "Mitsubishi", NameAR = "„Ì ”Ê»Ì‘Ì", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 19, Name = "Subaru", NameAR = "”Ê»«—Ê", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 20, Name = "Peugeot", NameAR = "»ÌÃÊ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 21, Name = "Renault", NameAR = "—Ì‰Ê", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 22, Name = "Fiat", NameAR = "›Ì« ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 23, Name = "Opel", NameAR = "√Ê»·", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 24, Name = "Suzuki", NameAR = "”Ê“ÊﬂÌ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 25, Name = "Seat", NameAR = "”Ì« ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 26, Name = "MG", NameAR = "≈„ ÃÌ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 27, Name = "Geely", NameAR = "ÃÌ·Ì", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 28, Name = "BYD", NameAR = "»Ì Ê«Ì œÌ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 29, Name = "JAC", NameAR = "Ã«ﬂ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 30, Name = "Chery", NameAR = "‘Ì—Ì", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 31, Name = "Jetour", NameAR = "ÃÌ Ê—", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 32, Name = "Speranza", NameAR = "”»Ì—«‰“«", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 33, Name = "BAIC", NameAR = "»«Ìﬂ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 34, Name = "Daewoo", NameAR = "œ«ÌÊ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 35, Name = "Dongfeng", NameAR = "œÊ‰€ ›Ì‰€", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 36, Name = "DFSK", NameAR = "œÌ ≈› ≈” ﬂÌÂ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 37, Name = "FAW", NameAR = "›«Ê", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 38, Name = "Foton", NameAR = "›Ê Ê‰", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 39, Name = "Lifan", NameAR = "·Ì›«‰", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 40, Name = "Proton", NameAR = "»—Ê Ê‰", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 41, Name = "Shalaby", NameAR = "‘·»Ì", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 42, Name = "Dayun", NameAR = "œ«ÌÊ‰", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 43, Name = "Volkswagen", NameAR = "›Ê·ﬂ” Ê«Ã‰", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 44, Name = "Skoda", NameAR = "”ﬂÊœ«", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 47, Name = "Lucid Motors", NameAR = "·Ê”Ìœ „Ê Ê—“", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 48, Name = "NIO", NameAR = "‰ÌÊ", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 49, Name = "XPeng", NameAR = "≈ﬂ” »‰Ã", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 50, Name = "Fisker", NameAR = "›Ì”ﬂ—", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 51, Name = "Polestar", NameAR = "»Ê·” «—", Expand = false , VehicleType = vehicletype.Car},
               new() { Id = 52, Name = "Faraday Future", NameAR = "›«—«œ«Ì ›ÌÊ ‘—", Expand = false , VehicleType = vehicletype.Car},
                new() { Id = 54, Name = "Harley-Davidson", NameAR = "Â«—·Ì œÌ›Ìœ”Ê‰", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 55, Name = "Yamaha", NameAR = "Ì«„«Â«", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 56, Name = "Honda", NameAR = "ÂÊ‰œ«", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 57, Name = "Kawasaki", NameAR = "ﬂ«Ê«”«ﬂÌ", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 58, Name = "Suzuki", NameAR = "”Ê“ÊﬂÌ", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 59, Name = "BMW Motorrad", NameAR = "»Ì ≈„ œ»·ÌÊ „Ê Ê", Expand = false, VehicleType =         vehicletype.Motorbike },
               new() { Id = 60, Name = "Ducati", NameAR = "œÊﬂ« Ì", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 61, Name = "KTM", NameAR = "ﬂÌ  Ì ≈„", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 62, Name = "Bajaj", NameAR = "»«Ã«Ã", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 63, Name = "Hero", NameAR = "ÂÌ—Ê", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 64, Name = "TVS", NameAR = " Ì ›Ì ≈”", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 65, Name = "Royal Enfield", NameAR = "—ÊÌ«· ≈‰›Ì·œ", Expand = false, VehicleType =      vehicletype.Motorbike },
               new() { Id = 66, Name = "Aprilia", NameAR = "√»—Ì·Ì«", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 67, Name = "Benelli", NameAR = "»Ì‰Ì··Ì", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 68, Name = "CFMoto", NameAR = "”Ì ≈› „Ê Ê", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 69, Name = "Vespa", NameAR = "›Ì”»«", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 70, Name = "SYM", NameAR = "≈” Ê«Ì ≈„", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 71, Name = "Lifan", NameAR = "·Ì›«‰", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 72, Name = "Zontes", NameAR = "“Ê‰ ”", Expand = false, VehicleType = vehicletype.Motorbike },
               new() { Id = 73, Name = "Nissan Leaf", NameAR = "‰Ì”«‰ ·Ì›", Expand = false, VehicleType = vehicletype.ElectricCar },
               new() { Id = 74, Name = "Chevrolet Bolt", NameAR = "‘Ì›—Ê·ÌÂ »Ê· ", Expand = false, VehicleType =          vehicletype.ElectricCar },
               new() { Id = 75, Name = "BMW i", NameAR = "»Ì ≈„ œ»·ÌÊ ¬Ì", Expand = false, VehicleType =  vehicletype.ElectricCar },
               new() { Id = 76, Name = "Audi e-tron", NameAR = "√ÊœÌ ≈Ì  —Ê‰", Expand = false, VehicleType =      vehicletype.ElectricCar },
               new() { Id = 77, Name = "Jaguar I-Pace", NameAR = "Ã«ﬂÊ«— ¬Ì-»Ì”", Expand = false, VehicleType =         vehicletype.ElectricCar },
               new() { Id = 78, Name = "Rivian", NameAR = "—Ì›Ì«‰", Expand = false, VehicleType = vehicletype.ElectricCar },
               new() { Id = 79, Name = "Lucid Motors", NameAR = "·Ê”Ìœ „Ê Ê—“", Expand = false, VehicleType =       vehicletype.ElectricCar },
               new() { Id = 80, Name = "NIO", NameAR = "‰ÌÊ", Expand = false, VehicleType = vehicletype.ElectricCar },
               new() { Id = 81, Name = "XPeng", NameAR = "≈ﬂ” »‰Ã", Expand = false, VehicleType = vehicletype.ElectricCar },
               new() { Id = 82, Name = "Polestar", NameAR = "»Ê·” «—", Expand = false, VehicleType = vehicletype.ElectricCar },
               new() { Id = 83, Name = "Faraday Future", NameAR = "›«—«œ«Ì ›ÌÊ ‘—", Expand = false, VehicleType =           vehicletype.ElectricCar },
               new() { Id = 84, Name = "Tesla", NameAR = " ”·«", Expand = false, VehicleType = vehicletype.ElectricCar },
               new() { Id = 85, Name = "VinFast", NameAR = "›Ì‰›«” ", Expand = false, VehicleType = vehicletype.ElectricCar }

            });
        }
    }
}
